# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BackChat
email: backchat2016@gmail.com
publicurl: "http://backchat.kefw.org"
description: >
  This is the official website of the King Edward VI Five Ways School
  Magazine.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://localhost:4000"
url: "" # the base hostname & protocol for your site
#url: "http://ir-g.uk/kefwmag.github.io"
# Build settings
markdown: kramdown
permalink: "/:categories/:year/:month/:day/:title/"

cats:
  news: "News"
  sports: "Sports"
  tech: "Technology"
  lifestyle: "Lifestyle"
  arts: "Arts &amp; Entertainment"
  ama: "Agony Aunt"

collections:
  authors:
    output: true
  editions:
    output: true

defaults:
  - scope:
      path: ""
      type: authors
    values:
      useTitle: true
      layout: author
  - scope:
      path: ""
      type: editions
    values:
      useTitle: true
      layout: edition
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: ""
      type: pages
    values:
      layout: default
