# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: KEFW Magazine
email: notyet@implemented.com
description: >
  This is the official website of the King Edward VI Five Ways School
  Magazine.
baseurl: "" # the subpath of your site, e.g. /blog
#url: "https://kefwmag.github.io" # the base hostname & protocol for your site
url: "http://ir-g.uk/kefwmag.github.io"
# Build settings
markdown: kramdown

cats:
  sports: "Sports"
  lifestyle: "Lifestyle"
  arts: "Arts & Entertainment"
  news: "News"
  tech: "Technology"
